import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Navbar from '@/components/Navigation'
import { AspectThemeProvider } from '@/components/ThemeProvider'
// import '../globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`bg-primary-50 dark:bg-primary-950 font-sans`} suppressHydrationWarning={true}>
        <AspectThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            <Navbar />
            {children}
        </AspectThemeProvider>
      </body>
    </html>
  )
}
