import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { AspectThemeProvider } from '@/components/ThemeProvider'
// import '../globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (

    <AspectThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
      <div className={`bg-primary-50 dark:bg-primary-950 text-primary-800 dark:text-primary-200 font-sans`}>
        {children}
        </div>
    </AspectThemeProvider>
  )
}
