import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { AspectThemeProvider } from '@/components/ThemeProvider'
import { Montserrat } from 'next/font/google'
// import '../globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (

    <AspectThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
      <div className={`bg-primary text-primary-foreground ${montserrat.className}`}>
        {children}
        </div>
    </AspectThemeProvider>
  )
}
